import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline-variant': '#48474b',
        'on-surface': '#f0edf1',
        'on-error': '#490013',
        'tertiary-container': '#fb81ae',
        'primary-fixed': '#F5CC40',
        'inverse-on-surface': '#555458',
        'error-dim': '#d73357',
        'primary-container': '#B8960A',
        'surface-dim': '#0e0e11',
        secondary: '#00e3fd',
        'inverse-primary': '#8B7000',
        'tertiary-fixed-dim': '#f57ca9',
        'surface-container-high': '#1f1f23',
        primary: '#E8B800',
        'on-tertiary-fixed': '#37001a',
        'secondary-container': '#006875',
        'surface-container-highest': '#25252a',
        'error-container': '#a70138',
        'secondary-dim': '#00d4ec',
        'on-background': '#f0edf1',
        'surface-container-low': '#131316',
        'on-secondary-fixed': '#003a42',
        'on-error-container': '#ffb2b9',
        'surface-bright': '#2c2c30',
        'surface-tint': '#E8B800',
        surface: '#0e0e11',
        tertiary: '#ff96bb',
        'primary-dim': '#C49A00',
        'on-secondary-container': '#e8fbff',
        'on-primary-fixed': '#000000',
        'surface-container': '#19191d',
        'primary-fixed-dim': '#D4AF37',
        'on-primary': '#1A1000',
        'on-tertiary-container': '#59002e',
        'on-secondary': '#004d57',
        'surface-variant': '#25252a',
        'tertiary-dim': '#ee77a3',
        outline: '#767579',
        'tertiary-fixed': '#ff8db6',
        'secondary-fixed-dim': '#00d7f0',
        'secondary-fixed': '#26e6ff',
        'on-surface-variant': '#acaaae',
        'on-primary-fixed-variant': '#7A6000',
        error: '#ff6e84',
        background: '#0e0e11',
        'on-primary-container': '#FFF3D0',
        'inverse-surface': '#fcf8fd',
        'on-tertiary-fixed-variant': '#70103e',
        'on-secondary-fixed-variant': '#005964',
        'on-tertiary': '#690939',
      },
      fontFamily: {
        headline: ['var(--font-epilogue)', 'sans-serif'],
        body: ['var(--font-manrope)', 'sans-serif'],
        label: ['var(--font-manrope)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      keyframes: {
        'graphic-eq': {
          '0%, 100%': { transform: 'scaleY(0.3)' },
          '50%': { transform: 'scaleY(1)' },
        },
        'slide-up': {
          from: { transform: 'translateY(100%)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
      animation: {
        'eq-bar-1': 'graphic-eq 0.8s ease-in-out infinite 0.0s',
        'eq-bar-2': 'graphic-eq 0.8s ease-in-out infinite 0.2s',
        'eq-bar-3': 'graphic-eq 0.8s ease-in-out infinite 0.4s',
        'slide-up': 'slide-up 0.3s ease-out',
        'fade-in': 'fade-in 0.4s ease-out',
      },
    },
  },
  plugins: [],
}

export default config
